- name: Set cpu_send.sh
  copy:
    src: cpu_send.sh
    dest: /home/ec2-user/script/cpu_send.sh
    mode: 0700
    owner: ec2-user
    group: ec2-user

- name: Cron cpu_send.sh
  cron:
    name: "cpu_send"
    minute: "*/1"
    job: "/home/ec2-user/script/cpu_send.sh"
    user: ec2-user
