AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ProjectId:
    Description: "Project name id."
    Type: String
    AllowedPattern: '^[a-zA-Z0-9-/:-@\[-\`\{-\~]+$'
    ConstraintDescription: "InvalidValue[ProjectId]"
    Default: kadai
  EnvironmentType:
      Description: The environment type
      Type: String
      Default: prod
      AllowedValues:
        - prod
      ConstraintDescription: must be a prod or test
  Email:
    Description: Email Address.
    Type: String
    Default: test@example.com

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "${ProjectId}-${EnvironmentType}-SNSTopic"
      TopicName: !Sub "${ProjectId}-${EnvironmentType}-SNSTopic"
  SNSSubscriptionEmail:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref Email
      Protocol: email
      TopicArn: !Ref SNSTopic
  SNSSubscriptionSQS:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: {"Fn::ImportValue": !Sub "${ProjectId}-${EnvironmentType}-Queue"}
      Protocol: sqs
      TopicArn: !Ref SNSTopic
