AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  KeyPairName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: SSH keyPair
  MyUserPassword:
    Description: 'password'
    Type: String
    MinLength: '8'
    MaxLength: '18'
    AllowedPattern: ^[a-zA-Z0-9]*$
    ConstraintDescription: password
    NoEcho: true
  Email:
    Description: Email Address.
    Type: String
    Default: test@example.com

Resources:
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/<バケット名>/IAM.yml

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/<バケット名>/VPC.yml

  SecurityGroup:
    DependsOn: VPC
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/<バケット名>/SecurityGroup.yml

  EC2:
    DependsOn: SecurityGroup
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/<バケット名>/EC2.yml
      Parameters:
        KeyPairName: !Ref KeyPairName

  ALB:
    DependsOn: EC2
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/<バケット名>/ALB.yml

  RDS:
    DependsOn: SecurityGroup
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/<バケット名>/RDS.yml
      Parameters:
        MyUserPassword: !Ref MyUserPassword

  SQS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/<バケット名>/SQS.yml

  SNS:
    Type: AWS::CloudFormation::Stack
    DependsOn: SQS
    Properties:
      TemplateURL: https://s3.amazonaws.com/<バケット名>/SNS.yml
      Parameters:
        Email: !Ref Email
