- name: Set cpu_recend.sh
  copy:
    src: cpu_recend.sh
    dest: /home/ec2-user/script/cpu_recend.sh
    mode: 0700
    owner: ec2-user
    group: ec2-user

- name: Cron cpu_recend.sh
  cron:
    name: "cpu_recend"
    minute: "*/1"
    job: "/home/ec2-user/script/cpu_recend.sh"
    user: ec2-user
